### ISSUE TITLE
Can't Install on debian server

### ISSUE THREAD

**Issue by hiperbolt** [typicode/stop-server#13]
I encontered two issues, first its the fact that in debian node doesnt exist, and the program is calling for node instead of nodejs; I fixed it by making a symlink.
Second issue I encontered I still can't fix:
## root@chronos2:~# npm install -g stop-server

> stop-server@0.3.0 uninstall /usr/local/lib/node_modules/stop-server
> node bin stop

Error: EACCES, permission denied '/root/.config/configstore/update-notifier-stop-server.json'
You don't have access to this file.

```
at Object.fs.openSync (fs.js:436:18)
at Object.fs.readFileSync (fs.js:290:15)
at Object.create.all.get (/usr/local/lib/node_modules/stop-server/node_modules/update-notifier/node_modules/configstore/index.js:34:26)
at Object.Configstore (/usr/local/lib/node_modules/stop-server/node_modules/update-notifier/node_modules/configstore/index.js:27:44)
at new UpdateNotifier (/usr/local/lib/node_modules/stop-server/node_modules/update-notifier/index.js:34:17)
at module.exports (/usr/local/lib/node_modules/stop-server/node_modules/update-notifier/index.js:123:23)
at Object.<anonymous> (/usr/local/lib/node_modules/stop-server/bin.js:14:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
```

npm WARN continuing anyway stop-server@0.3.0 uninstall: `node bin stop`
npm WARN continuing anyway Exit status 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
/usr/local/bin/stop-server -> /usr/local/lib/node_modules/stop-server/bin.js
stop-server@0.3.0 /usr/local/lib/node_modules/stop-server
├── network-address@1.1.0
├── sudo-block@1.2.0 (is-root@1.0.0, is-docker@1.0.1)
├── power-off@1.0.1 (is-windows@0.2.0, is-osx@1.0.2, is-linux@1.0.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── user-startup@0.1.1 (untildify@2.1.0, mkdirp@0.5.1)
├── yargs@3.32.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1.4, os-locale@1.4.0, string-width@1.0.1, cliui@3.2.0)
├── sleep-mode@1.1.0 (is-windows@0.1.1, is-osx@1.0.2, is-linux@1.0.1, meow@3.7.0)
├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.6, merge-descriptors@1.0.1, fresh@0.3.0, methods@1.1.2, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, cookie@0.1.5, parseurl@1.3.1, etag@1.7.0, content-type@1.0.2, content-disposition@0.5.1, depd@1.1.0, on-finished@2.3.0, finalhandler@0.4.1, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.10, send@0.13.1, serve-static@1.10.3, type-is@1.6.13, accepts@1.2.13)
├── update-notifier@0.5.0 (is-npm@1.0.0, string-length@1.0.1, repeating@1.1.3, semver-diff@2.1.0, configstore@1.4.0, latest-version@1.0.1)
└── got@4.2.0 (lowercase-keys@1.0.0, timed-out@2.0.0, is-redirect@1.0.0, is-plain-obj@1.1.0, prepend-http@1.0.4, is-stream@1.1.0, unzip-response@1.0.0, object-assign@3.0.0, node-status-codes@1.0.0, create-error-class@2.0.1, pinkie-promise@1.0.0, parse-json@2.2.0, read-all-stream@3.1.0, duplexify@3.4.3)

What I can gather is that it wants a superior version of node, which I can't install.

**Comment by derhuerst** [comment]
> I encontered two issues, first its the fact that in debian node doesnt exist, and the program is calling for node instead of nodejs; I fixed it by making a symlink.

`node` is the correct name of the Node.js executable. This isn't wrong.

> `Error: EACCES, permission denied '/root/.config/configstore/update-notifier-stop-server.json'`

This seems to be a problem with `configstore`. See https://github.com/yeoman/configstore/issues/6

> What I can gather is that it wants a superior version of node, which I can't install.

This is just a warning from npm. It may break the installation at some point in the future, but the reason why it fails now is the issue I mentioned above, not this one.

**Comment by hiperbolt** [comment]
Thanks I'll look into second and third point, as for the first point; in debian node isnt the name of Node.js executable. It is wrong. See it here: http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

**Comment by derhuerst** [comment]
@hiperbolt On Debian/Ubuntu-based distros, the _package_ is called `nodejs`, but the _executable_ is called `node`.

**Comment by deathstar** [comment]
looks like a permissions error, try using sudo su
